version: '2.1'

services:

  app:
    image: ${IMAGE}:${IMAGE_VER}
    ports:
      - "${SERVICE_PORT}:53"
      - "${SERVICE_PORT}:53/udp"
    restart: always
    networks:
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.port=8081"
      - "traefik.frontend.rule=Host:${APP_SITE}"
      - "traefik.frontend.auth.basic.users=${AUTH}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /usr/sbin/pdns_server
    command:
      --master --daemon=no --chroot=/ --socket-dir=/var/run
      --launch=bind --launch+=gpgsql --gpgsql-dbname=${DB_USER} --gpgsql-user=${DB_USER}
      --gpgsql-host=db --gpgsql-password=${DB_PASS}
      --webserver --webserver-address=0.0.0.0 --webserver-port=8081 --webserver-allow-from=0.0.0.0/0

networks:
  lan:
    external:
      name: ${DCAPE_NET}
