version: '2.1'

services:

  pdns-app:
    image: ${IMAGE}:${IMAGE_VER}
    ports:
      - "${SERVICE_PORT}:53"
      - "${SERVICE_PORT}:53/udp"
    restart: always
    networks:
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pdns-app.rule=Host(`${APP_SITE}`)"
      - "traefik.http.routers.pdns-app.middlewares=narra"
      - "traefik.http.services.pdns-app.loadbalancer.server.port=8081"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/null:/etc/pdns.conf
    command:
      --master --daemon=no --chroot=/ --socket-dir=/var/run --launch=gpgsql
      --webserver --webserver-address=0.0.0.0 --webserver-port=8081 --webserver-allow-from=0.0.0.0/0
      --gpgsql-host=db --gpgsql-dbname=${PGDATABASE} --gpgsql-user=${PGUSER} --gpgsql-password=${PGPASSWORD}
#--launch=bind
#  --launch+=gpgsql
networks:
  lan:
    external:
      name: ${DCAPE_NET}
